name: Run Unit Tests
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        storage:
          - MEMORY
          - ETCD
          - POSTGRES
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Install docker compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose make
      - name: Run unit tests
        run: make unittest # this inherits STORAGE from the environment via Makefile directives
